### ISSUE TITLE
Add net-utils and can-utils to the default container

### ISSUE THREAD

**Issue by Quinn1876** [waterloop/firmware-vagrant#1]
`net-utils` and `can-utils` are both very helpful libraries for working on the communications side of development. Having them installed by default will save a lot of time helping people who are not aware of these tools to begin with (aka we don't want to spend time in calls walking them through installing them, we want to spend time showing them how to use them). I will link this to a clickup task as well.

**Comment by RyanMah123** [comment]
Anyone can feel free to just add it to provision_box.sh
